---
#crear usuario y grupo
#instalar java
#crear directorio para tomcat
#descargar y descomprimir el software
#asociar usuario y grupo
#crear fichero para arranque
#arrancar el servicio

- name: instalar tomcat 10
  hosts: anode
  vars:
    url_descarga: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.34/bin/apache-tomcat-10.1.34.tar.gz

  tasks:

    - name: crear usuario
      user:
        name: tomcat

    - name: crear grupo
      group:
        name: tomcat

    - name: instalar java
      apt:
        name: default-jdk
        state: present

    - name: crear directorio para grupo
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes

    - name: descarga y descomprimir
      unarchive:
        src: "{{url_descarga}}"
        dest: /opt/tomcat
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Cambiar el propietario del directorio de Tomcat
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

      
    - name: Cambiar el propietario del directorio de Tomcat
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat

    - name: Crear uin fichero de servicio
      copy: 
        content: |-
          [Unit]
          Description=Mi Servicio de TOMCAT
          Requires=network.target
          After=network.target
          
          [Service]
          Type=forking
          User=tomcat
          Environment="CATALINA_PID=/opt/tomcat/logs/tomcat.pid"
          Environment="CATALINA_BASE=/opt/tomcat"
          Environment="CATALINA_HOME=/opt/tomcat"
          Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
          ExecStart=/opt/tomcat/bin/startup.sh
          ExecStop=/opt/tomcat/bin/shutdown.sh
          Restart=on-abnormal
          
          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/tomcat.service

    - name: Arrancar Tomcat
      service:
        name: tomcat
        state: started

...